apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
spec:
  replicas: 1
  selector:
   matchLabels:
    app: httpserver
  template:
    metadata:
      name: httpserver
      labels:
        app: httpserver
    spec:
      #等待容器响应 syscall.SIGTERM
      terminationGracePeriodSeconds: 40
      containers:
        - name: httpserver
          image: king607267/cnl-httpserver:v3.0
          ports:
            - containerPort: 7000
          readinessProbe:
            httpGet:
              port: 7000
              path: /healthz
            initialDelaySeconds: 20
            periodSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
