FROM golang AS build

WORKDIR /httpserver/

COPY httpserver.go .

ENV CGO_ENABLED=0
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct

RUN GOOS=linux go build -installsuffix cgo -o httpserver httpserver.go

FROM alpine

COPY --from=build /httpserver/httpserver /httpserver/httpserver

EXPOSE 7000

WORKDIR /httpserver/

ENTRYPOINT ["./httpserver"]