FROM golang AS build

WORKDIR /httpserver/

COPY httpserver.go .

ENV CGO_ENABLED=0
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct

RUN GOOS=linux go build -installsuffix cgo -o httpserver httpserver.go

FROM ubuntu

RUN apt-get -y update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install curl && rm -rf /var/lib/apt/lists/*

COPY --from=build /httpserver/httpserver /httpserver/httpserver

EXPOSE 7000

WORKDIR /httpserver/

ENTRYPOINT ["./httpserver"]